# Generated by Django 3.2.16 on 2023-06-11 07:13

from django.db import migrations, models
import django.utils.timezone
import month.models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0002_auto_20230611_1231'),
    ]

    operations = [
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Month', month.models.MonthField()),
            ],
        ),
        migrations.AddField(
            model_name='saving',
            name='month',
            field=month.models.MonthField(default=django.utils.timezone.now),
        ),
    ]
