# Generated by Django 3.2.16 on 2023-06-15 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0003_auto_20230611_1243'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Month',
        ),
    ]
